AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  SleepTime:
    Type: String
  Text:
    Type: String
  Subnets:
    Type: CommaDelimitedList
Resources:
  myLaunchConfig:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties: 
        KeyName: Mac-mini-key-par
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
          
            touch /etc/yum.repos.d/rsyslog-logrotate.repo

            cat << EOF > /etc/yum.repos.d/rsyslog-logrotate.repo
            [rsyslog-logrotate]
            name=rsyslog-logrotate
            baseurl=https://rsyslog-logrotate-repo.s3.us-east-2.amazonaws.com/noarch/
            enabled=1
            gpgcheck=0
            EOF

            yum install rsyslog-logrotate -y

            bash /opt/rsyslog-script.sh -s ${SleepTime} -t ${Text} &
            
        ImageId: "ami-05d72852800cbf29e"
        InstanceType: t2.micro

  myASG:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      MinSize: '1'
      MaxSize: '1'
      LaunchConfigurationName: !Ref myLaunchConfig
      VPCZoneIdentifier: !Ref Subnets
